# Fundamentos de Python

Python es un lenguaje de propósitos múltiples creado por el holandés [Guido van Rossum](https://gvanrossum.github.io/) en 1991.

Es un lenguaje de alto nivel, lo que significa que está optimizado para ser leído por personas en lugar de máquinas.

Es además un lenguaje interpretado, es decir que no se compila directamente a código máquina, sino que las instrucciones se ejecutan directamente mediante el intérprete de Python. Esto permite que se utilice de una manera interactiva, de manera tal que se pueda ejecutar cada línea de código a medida que se van escribiendo. Esto resulta muy útil para tareas que requieren mucha investigación, a diferencia de aquellas que requieren mucho diseño.

Python es un lenguaje de tipado dinámico, es decir, los tipos de datos de las variables son verificados en tiempo de ejecución y no es necesario especificarlos al momento de programar.

Si Python no está incluido por defecto en la distribución del sistema operativo, puede descargse [aquí](https://www.python.org/downloads/).

## Jupyter

[Jupyter Notebook](https://jupyter.org/) es una aplicación web *open-source* que permite crear y compartir documentos con "código vivo" de manera tal que se pueda escribir código, ejecutarlo inmediatamente y visualizar los resultados en la misma página, además de poder entrelazarlo con texto en formato [Markdown](https://es.wikipedia.org/wiki/Markdown).

Para instalarlo bastará con ejecutar las siguientes líneas en la terminal:
```console
$ python3 -m pip install --upgrade pip
$ python3 -m pip install jupyter
```
Una vez instalado se podrá ejecutar con el siguiente comando, que iniciará la aplicación en el navegador web:
```console
$ jupyter notebook
```

## Funciones

Asignación y suma de variables:

In [1]:
x = 1
y = 2
x + y

3

Al evaluar la variable `x` en otra celda se muestra el mismo resultado que antes:

In [2]:
x

1

Si quisiéramos imprimir más de una variable en la misma celda se puede utilizar `print` para cada una de ellas.

In [3]:
print(x)
print(y)
print(x + y)

1
2
3


`sumar_numeros` es una función que recibe dos números y devuelve su suma.

In [4]:
def sumar_numeros(x, y):
    return x + y

sumar_numeros(1, 2)

3

Se puede reescribir la función `sumar_numeros` de manera tal que acepte un tercer parámetro de manera opcional.

In [5]:
def sumar_numeros(x,y,z=None):
    if (z == None):
        return x + y
    else:
        return x + y + z

print(sumar_numeros(1, 2))
print(sumar_numeros(1, 2, 3))

3
6


Todos los parámetros opcionales deben ir al final de la declaración.

En el siguiente ejemplo la función `sumar_numeros` permite otro parámetro opcional más.

In [6]:
def sumar_numeros(x, y, z=None, flag=False):
    if (flag):
        print('El flag es verdadero.')
    if (z==None):
        return x + y
    else:
        return x + y + z
    
print(sumar_numeros(1, 2, flag=True))

El flag es verdadero.
3


Las funciones también pueden ser asignadas a variables y posteriormente ejecutadas directamente mediante las variables.

In [7]:
def sumar_numeros(x,y):
    return x+y

a = sumar_numeros
a(1,2)

3

## Tipos y colecciones

La ausencia de tipado estático en Python no significa que no existan tipos. Python tiene una función incorporada llamada `type` que muestra de qué tipo es una referencia dada. Algunos de los tipos más comunes son enteros (*int*), cadenas de caracteres (*str*), el tipo *None*, como también el tipo de funciones.

In [8]:
type('Esto es una cadena de caracteres')

str

In [9]:
type(None)

NoneType

In [10]:
type(1)

int

In [11]:
type(1.0)

float

In [12]:
type(sumar_numeros)

function

<br>
Existen tres tipos principales de colecciones nativas de Python:
- tuplas,
- listas y
- diccionarios

Las **tuplas** son estructuras de datos inmutables. Es decir, una tupla contiene elementos en un determinado orden pero no puede ser alterada una vez creada. Se crean utilizando paréntesis y se pueden incluir datos de tipos distintos.

In [13]:
x = (1, 'a', 2, 'b')
type(x)

tuple

Las **listas** son estructuras de datos similares a las tuplas pero son mutables. Es decir, se puede modificar su longitud, su cantidad de elementos y los valores de cada uno de ellos.

In [14]:
x = [1, 'a', 2, 'b']
type(x)

list

Existen muchas maneras de alterar el contenido de una lista. Una de ellas es mediante la función `append()`, que permite agregar nuevos elementos al final de la lista.

In [15]:
x.append(3.3)
x

[1, 'a', 2, 'b', 3.3]

Tanto las tuplas como las listas son tipos iterables, de manera tal que se puede escribir ciclos para recorrer cada uno de sus elementos. La forma más común es mediante la sentencia `for`, similar a otros lenguajes pero no hace falta especificar ningún tipo de dato.

In [16]:
for item in x:
    print(item)

1
a
2
b
3.3


Las listas y las tuplas también se pueden acceder como los arreglos en otros lenguajes, es decir, mediante corchetes.
Por lo tanto, otra manera de recorrer una lista es incrementando un contador desde la posición cero hasta aquella  dada por su tamaño, mediante la función `len()`.

In [17]:
i = 0
while( i != len(x) ):
    print(x[i])
    i = i + 1

1
a
2
b
3.3


Las listas y tuplas soportan también algunas operaciones matemáticas básicas. Por ejemplo, el signo `+` concatena dos listas y el signo `*` repite su contenido la cantidad de veces especificada.

In [18]:
[1, 2] + [3, 4]

[1, 2, 3, 4]

In [19]:
[1, 2] * 3

[1, 2, 1, 2, 1, 2]

El operador `in` permite verificar si un elemento pertenece a la lista.

In [20]:
1 in [1, 2, 3]

True

Quizás las operaciones más interesantes que se pueden hacer con listas son las de rebanar (*slicing*). En Python el operador de índice (corchete) adminte múltiples valores. El primer parámetro es la ubicación de inicio y el segundo parámetro indica el fin de la rebanada.

In [21]:
x = 'Esto es una cadena de caracteres'
print(x[0])   # primer caracter
print(x[0:1]) # primer caracter pero explicitando el final de la rebanada
print(x[0:2]) # primeros dos caracteres

E
E
Es


Esto devolverá el último elemento de la lista:

In [22]:
x[-1]

's'

Esto devolverá la porción que comienza con el sexto elemento desde el final y deteniéndose en el segundo elemento desde el final.

In [23]:
x[-6:-2]

'cter'

Esto es una porción desde el principio de la cadena de caracteres hasta el tercer elemento.

In [24]:
x[:3]

'Est'

Y esto obtiene una porción de la lista desde el cuarto elemento hasta el final.

In [25]:
x[3:]

'o es una cadena de caracteres'

Las cadenas de caracteres son simplemente listas que contienen elementos de tipo caracter. Por lo tanto, todas las operaciones que se pueden hacer sobre una lista también se pueden realizar sobre una cadena de caracteres.

In [26]:
primer_nombre = 'Juan'
apellido = 'Pérez'

print(primer_nombre + ' ' + apellido)
print(primer_nombre * 3)
print('Juan' in primer_nombre)

Juan Pérez
JuanJuanJuan
True


La función `split` devuelve una lista de todas las palabras de una cadena de caracteres o una lista separada por un caracter determinado.

In [27]:
primer_nombre = 'Juan Pablo Pérez'.split(' ')[0] # [0] selecciona el primer elemento de la lista
apellido = 'Juan Pablo Pérez'.split(' ')[-1] # [-1] selecciona el último elemento de la lista
print(primer_nombre)
print(apellido)

Juan
Pérez


Es necesario asegurarse de que todos las variables sean convertidas a cadenas de caracteres antes de concatenarlas.

In [28]:
'Juan' + str(2)

'Juan2'

<br>
Los **diccionarios** son similares a las listas y tuplas en el sentido de que contienen una colección de elementos, pero cada uno de sus elementos tiene una etiqueta y no tienen un orden. Esto significa que por cada *valor* que se agregue a un diccionario se debe proveer también su correspondiente *clave*.

In [29]:
x = {'Juan Pérez': 'jperez@gmail.com',
     'Bill Gates': 'billg@microsoft.com'}
x['Juan Pérez'] # se obtiene un valor mediante el operador de índices

'jperez@gmail.com'

In [30]:
x['María González'] = None
x['María González']

<br>
Existen varias maneras de recorrer un diccionario. Por ejemplo, se puede recorrer sobre cada clave y acceder al valor en cada iteración.

In [31]:
for nombre in x:
    print(x[nombre])

jperez@gmail.com
billg@microsoft.com
None


También se puede iterar directamente sobre los valores ignorando las claves.

In [32]:
for email in x.values():
    print(email)

jperez@gmail.com
billg@microsoft.com
None


<br>
Finalmente, también es posible recorrer tanto la clave como el valor del elemnto al mismo tiempo.

In [33]:
for nombre, email in x.items():
    print(nombre + ' ' + str(email))

Juan Pérez jperez@gmail.com
Bill Gates billg@microsoft.com
María González None


Este último ejemplo incluye el concepto de desempaquetado, que consiste en asignar en un único paso el contenido de una colección a varias variables.

In [34]:
x = ('Juan', 'Pérez', 'jperez@gmail.com')
primer_nombre, apellido, email = x

In [35]:
primer_nombre

'Juan'

In [36]:
apellido

'Pérez'

In [37]:
email

'jperez@gmail.com'

Es necesario asegurarse de que la cantidad de valores a desempaquetar coincida con la cantidad de variables asignadas para que no se produzcan errores.

## Más sobre cadenas de caracteres

Python tiene un método incorporado para facilitar el formato de las cadenas de caracteres.

In [38]:
registro_ventas = {
    'precio': 3.24,
    'cant_elementos': 4,
    'persona': 'Juan'}

sentencia_ventas = '{} compró {} elemento(s) a un precio de {} cada uno, por un total de {}.'

print(sentencia_ventas.format(registro_ventas['persona'],
                              registro_ventas['cant_elementos'],
                              registro_ventas['precio'],
                              registro_ventas['cant_elementos'] * registro_ventas['precio']))


Juan compró 4 elemento(s) a un precio de 3.24 cada uno, por un total de 12.96.


## Lectura y escritura de archivos CSV

El archivo `mpg.csv` contiene datos sobre el consumo de combustible de 234 automóbiles distintos.

* mpg : millas por galón
* class : clasificación del automóbil
* cty : consumo de mpg en ciudad
* cyl : cantidad de cilindros
* displ : cilindrada (en litros)
* drv : f = tracción delantera, r = tracción trasera, 4 = 4x4
* fl : tipo de combustible (e = ethanol E85, d = diesel, r = regular, p = premium, c = CNG)
* hwy : consumo de mpg en autopista
* manufacturer : fabricante del auto
* model : modelo del auto
* trans : tipo de transmisión
* year : año de fabricación del automóvil

In [39]:
import csv

%precision 2

with open('datos/mpg.csv') as csvfile:
    mpg = list(csv.DictReader(csvfile))
    
mpg[:2] # Muestra los primeros dos diccionarios de la lista

[OrderedDict([('', '1'),
              ('manufacturer', 'audi'),
              ('model', 'a4'),
              ('displ', '1.8'),
              ('year', '1999'),
              ('cyl', '4'),
              ('trans', 'auto(l5)'),
              ('drv', 'f'),
              ('cty', '18'),
              ('hwy', '29'),
              ('fl', 'p'),
              ('class', 'compact')]),
 OrderedDict([('', '2'),
              ('manufacturer', 'audi'),
              ('model', 'a4'),
              ('displ', '1.8'),
              ('year', '1999'),
              ('cyl', '4'),
              ('trans', 'manual(m5)'),
              ('drv', 'f'),
              ('cty', '21'),
              ('hwy', '29'),
              ('fl', 'p'),
              ('class', 'compact')])]

`csv.Dictreader` lee cada línea del archivo CSV y crea diccionarios a partir de ellas en donde los nombres de las columnas pasan a ser las claves de los diccionarios.

Mediante `len` se observa que la lista está constituida por 234 diccionarios.

In [40]:
len(mpg)

234

El método `keys` devuelve los nombres de las columnas del CSV.

In [41]:
mpg[0].keys()

odict_keys(['', 'manufacturer', 'model', 'displ', 'year', 'cyl', 'trans', 'drv', 'cty', 'hwy', 'fl', 'class'])

De la siguiente manera se obtiene el consumo de combustible promedio en ciudad sobre todos los autos. Como todos los valores de los diccionarios son cadenas de caracteres, es necesario convertirlos a *float*s primero.

In [42]:
sum(float(d['cty']) for d in mpg) / len(mpg)

16.86

Similarmente se puede conseguir el valor  de consumo de combustible promedio en autopista de todos los autos.

In [43]:
sum(float(d['hwy']) for d in mpg) / len(mpg)

23.44

Utilizando `set` se obtiene los valores únicos para un determinado número de cilindros que tienen los autos del conjunto de datos.

In [44]:
cylinders = set(d['cyl'] for d in mpg)
cylinders

{'4', '5', '6', '8'}

En este otro ejemplo más complejo se agrupan primero los autos por el número de cilindros y se calcula el millaje por galón (mpg) promedio de cada grupo.

In [45]:
CtyMpgByCyl = []

for c in cylinders: # iterar sobre todos los niveles de cilindros
    summpg = 0
    cyltypecount = 0
    for d in mpg: # iterar sobre todos los diccionarios
        if d['cyl'] == c: # si la cantidad de cilindros coincide,
            summpg += float(d['cty']) # sumar el consumo de mpg en ciudad
            cyltypecount += 1 # incrementar el contador
    CtyMpgByCyl.append((c, summpg / cyltypecount)) # agregar la tupla ('cilindro', 'mpg promedio')

CtyMpgByCyl.sort(key=lambda x: x[0])
CtyMpgByCyl

[('4', 21.01), ('5', 20.50), ('6', 16.22), ('8', 12.57)]

Para realizar otro ejemplo similar, primero se utiliza `set` para devolver los valores únicos para las clases del conjunto de datos.

In [46]:
vehicleclass = set(d['class'] for d in mpg) # cuáles son los tipos de clases
vehicleclass

{'2seater', 'compact', 'midsize', 'minivan', 'pickup', 'subcompact', 'suv'}

Luego, se calcula el mpg en autopista para cada clase de vehículo del conjunto de datos.

In [47]:
HwyMpgByClass = []

for t in vehicleclass: # iterar sobre todas las clases de vehículos
    summpg = 0
    vclasscount = 0
    for d in mpg: # iterar sobre todos los diccionarios
        if d['class'] == t: # si la clase de vehículo coincide,
            summpg += float(d['hwy']) # agregarlo al mpg
            vclasscount += 1 # incrementar el contador
    HwyMpgByClass.append((t, summpg / vclasscount)) # agregar la tupla ('class', 'avg mpg')

HwyMpgByClass.sort(key=lambda x: x[1])
HwyMpgByClass

[('pickup', 16.88),
 ('suv', 18.13),
 ('minivan', 22.36),
 ('2seater', 24.80),
 ('midsize', 27.29),
 ('subcompact', 28.14),
 ('compact', 28.30)]

## Fechas y horarios

In [48]:
import datetime as dt
import time as tm

El método `time` devuelve el tiempo actual en segundos desde la fecha de referencia (1 de enero de 1970).

In [49]:
tm.time()

1548599792.02

Se puede obtener una marca de tiempo legible mediante el método `fromtimestamp`.

In [50]:
dtnow = dt.datetime.fromtimestamp(tm.time())
dtnow

datetime.datetime(2019, 1, 27, 11, 36, 32, 842660)

El objeto datetime tiene los atributos correspondientes al año, mes, día, hora, minutos y segundos, que pueden ser accedidos por separado.

In [51]:
dtnow.year, dtnow.month, dtnow.day, dtnow.hour, dtnow.minute, dtnow.second

(2019, 1, 27, 11, 36, 32)

`timedelta` es una duración que expresa la diferencia entre dos fechas.

In [52]:
delta = dt.timedelta(days = 100) # Crea un timedelta de 100 días
delta

datetime.timedelta(100)

`date.today` devuelve la fecha local actual.

In [53]:
today = dt.date.today()
today

datetime.date(2019, 1, 27)

In [54]:
today - delta # La fecha hace 100 días

datetime.date(2018, 10, 19)

In [55]:
today > today-delta # comparación de fechas

True

## Objectos y la función map()

Una clase en Python se puede definir mediante la palabra reservada `class` seguida del nombre de la clase comenzando con letra mayúscula. Todo lo que esté debajo de esta declaración e indentado estará dentro del alcance de la clase.

In [56]:
class Person:
    departmento = 'Computación' # una variable de clase

    def set_nombre(self, nuevo_nombre): # un método
        self.nombre = nuevo_nombre
    def set_ubicacion(self, nueva_ubicacion):
        self.ubicacion = nueva_ubicacion

In [57]:
person = Person()
person.set_nombre('Juan Pérez')
person.set_ubicacion('San Telmo, CABA, Argentina')
print('{} vive en {} y trabaja en el departamento de {}.'.format(person.nombre,
                                                                 person.ubicacion,
                                                                 person.departmento))

Juan Pérez vive en San Telmo, CABA, Argentina y trabaja en el departamento de Computación.


<br>
La función `map` es una de las bases de la programación funcional en Python. La programación funcional es un paradigma de programación en el cual se declaran explícitamente todos los parámetros que podrían cambiar a través de la ejecución de una determinada función.

La función `map` devuelve un iterador que aplica la función recibida por parámetro a acada elemento de la colección también recibida por parámetro.

El siguiente ejemplo se encarga de encontrar el valor mínimo de cada par de elementos de dos listas, pasando la función `min` como parámetro de la función `map`:

In [58]:
lista1 = [10.00, 11.00, 12.34, 2.34]
lista2 = [9.00, 11.10, 12.34, 2.01]
menor = map(min, lista1, lista2)
menor

La función `map` devuelve un objeto map, que es iterable, por lo cual se lo puede recorrer para visualizar los resultados:

In [59]:
for item in menor:
    print(item)

9.0
11.0
12.34
2.01


El siguiente ejemplo aplica una función a una lista de cadenas de caracteres obteniendo el título y el apellido de cada uno de los elementos:

In [60]:
personas = ['Dr. Emmet Brown', 'Dr. Otto Octavius', 'Dr. Victor Doom']

def obtener_titulo_y_apellido(personas):
    titulo = personas.split()[0]
    apellido = personas.split()[-1]
    return '{} {}'.format(titulo, apellido)

list(map(obtener_titulo_y_apellido, personas))

['Dr. Brown', 'Dr. Octavius', 'Dr. Doom']

## Lambda y comprensión de listas

"Lambda" es la manera que tiene Python para crear *funciones anónimas*. Son simplemente funciones como cualquier otra salvo que no tienen nombre. Su intención es la de ser ejecutadas una única vez y escritas rápidamente en una sola línea.

El siguiente ejemplo toma tres parámetros y suma los primeros dos:

In [61]:
mi_funcion = lambda a, b, c : a + b

In [62]:
mi_funcion(1, 2, 3)

3

En este caso la referencia a la función es guardada en la variable `mi_funcion` pero puede ser pasada directamente por parámetro en una función `map`.
Debido a que las funciones lambda están limitadas a una única expresión resultan ser mucho menos versátiles que las funciones definidas tradicionalmente. Sin embargo, resultan ser muy útiles para tareas sencillas de limpieza de datos.

Por ejemplo, teniendo la lista de personas de un ejemplo anterior se puede aplicar una función lambda para obtener los títulos y apellidos de cada persona de manera análoga a declarar la función:

In [63]:
personas = ['Dr. Emmet Brown', 'Dr. Otto Octavius', 'Dr. Victor Doom']

def obtener_titulo_y_apellido(persona):
    return persona.split()[0] + ' ' + persona.split()[-1]

# opción 1
for persona in personas:
    print(obtener_titulo_y_apellido(persona) == \
          (lambda x: x.split()[0] + ' ' + x.split()[-1])(persona))

# opción 2
list(map(obtener_titulo_y_apellido, personas)) == \
list(map(lambda persona: persona.split()[0] + ' ' + persona.split()[-1], personas))

True
True
True


True

<br>
Python provee además una manera más abreviada de manipular colecciones denominada comprensión de listas:

En el siguiente ejemplo realizamos una iteración de los números del 0 al 10 y agregamos a una lista aquellos que sean pares:

In [64]:
my_list = []
for number in range(0, 10):
    if number % 2 == 0:
        my_list.append(number)
my_list

[0, 2, 4, 6, 8]

Con comprensión de listas esto puede realizarse de una manera mucho más compacta y eficiente:

In [65]:
my_list = [number for number in range(0,10) if number % 2 == 0]
my_list

[0, 2, 4, 6, 8]

Otro ejemplo:

In [66]:
def times_tables():
    lst = []
    for i in range(10):
        for j in range (10):
            lst.append(i*j)
    return lst

times_tables() == [j*i for i in range(10) for j in range(10)]

True

El siguiente ejemplo crea una lista con todas las combinaciones posibles de cadenas de caracteres de cuatro elementos, de los cuales los primeros dos son dos letras minúsculas y los restantes son números:

In [67]:
minusculas = 'abcdefghijklmnopqrstuvwxyz'
digitos = '0123456789'

respuesta = [a+b+c+d for a in minusculas for b in minusculas for c in digitos for d in digitos]

respuesta[:8] # Muestra los primeros 8 resultados

['aa00', 'aa01', 'aa02', 'aa03', 'aa04', 'aa05', 'aa06', 'aa07']

<br>
## La biblioteca numérica de Python (NumPy)

[NumPy](http://www.numpy.org/) es un paquete muy utilizado en la comunidad de *data science* que nos permite trabajar eficientemente con vectores y matrices en Python.

In [68]:
import numpy as np

### Creación de vectores
Para crear un vector se puede simplemente crear primero una lista y convertirla a un vector:

In [69]:
lista = [1, 2, 3]
x = np.array(lista)
x

array([1, 2, 3])

También se puede pasar la lista por parámetro directamente:

In [70]:
y = np.array([4, 5, 6])
y

array([4, 5, 6])

Si por parámetro se pasa una lista de lista se pueden crear vectores multidimensionales:

In [71]:
m = np.array([[7, 8, 9], [10, 11, 12]])
m

array([[ 7,  8,  9],
       [10, 11, 12]])

Se puede acceder al atributo `shape` para averiguar las dimensiones del vector (filas, columnas): 

In [72]:
m.shape

(2, 3)

El método `arange` devuelve un vector con valores separados uniformemente dentro de un intervalo dado:

In [73]:
n = np.arange(0, 30, 2) # comienza en 0 hasta 30 yendo de 2 en 2
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

El método `reshape` devuelve un vector con los mismos valores pero con otra forma:

In [74]:
n = n.reshape(3, 5) # convierte a 3x5
n

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

El método `linspace` es muy similar a `arange` excepto que le decimos cuántos números deseamos que devuelva y se encargará de dividirlos uniformemente dentro del rango solicitado:

In [75]:
o = np.linspace(0, 4, 9) # devuelve 9 números separados uniformemente entre 0 y 4
o

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

El método `resize` cambia las dimensiones de un mismo vector:

In [76]:
o.resize(3, 3)
o

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])

NumPy también tiene varias otras funciones y atajos rápidos para crear vectores específicos.

El método `ones` devuelve un nuevo vector lleno de unos con las dimensiones especificadas:

In [77]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

El método `zeros` devuelve un vector lleno de ceros con las dimensiones especificadas:

In [78]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

El método `eye` devuelve un vector bidimensional con unos en la diagonal principal y ceros en las demás posiciones:

In [79]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

El método `diag` crea una matriz diagonal:

In [80]:
np.diag(y)

array([[4, 0, 0],
       [0, 5, 0],
       [0, 0, 6]])

Para crear una matriz con valores repetidos se pueden pasar listas repetidas o el método `repeat` de NumPy:

In [81]:
np.array([1, 2, 3] * 3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [82]:
np.repeat([1, 2, 3], 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

### Combinación de vectores

In [83]:
p = np.ones([2, 3], int)
p

array([[1, 1, 1],
       [1, 1, 1]])

El método `vstack` permite apilar arreglos verticalmente:

In [84]:
np.vstack([p, 2*p])

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2]])

Análogamente, el método `hstack` permite apilar arreglos en secuencia horizontal:

In [85]:
np.hstack([p, 2*p])

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

### Operaciones
Los operadores `+`, `-`, `*`, `/` y `**` permiten realizar adiciones, substracciones, multiplicaciones, divisiones y potenciaciones sobre cada elemento de un vector:

In [108]:
print(x + y) #  [1 2 3] + [4 5 6] = [5  7  9]
print(x - y) #  [1 2 3] - [4 5 6] = [-3 -3 -3]

[5 7 9]
[-3 -3 -3]


In [109]:
print(x * y) #  [1 2 3] * [4 5 6] = [4  10  18]
print(x / y) #  [1 2 3] / [4 5 6] = [0.25  0.4  0.5]

[ 4 10 18]
[0.25 0.4  0.5 ]


In [110]:
print(x**2) #  [1 2 3] ^2 =  [1 4 9]

[1 4 9]


#### Producto escalar

$ \begin{bmatrix}x_1 \ x_2 \ x_3\end{bmatrix}
\cdot
\begin{bmatrix}y_1 \\ y_2 \\ y_3\end{bmatrix}
= x_1 y_1 + x_2 y_2 + x_3 y_3$

In [111]:
x.dot(y) # producto escalar  1*4 + 2*5 + 3*6

32

In [112]:
z = np.array([y, y**2])
print(len(z)) # número de filas en la matriz

2


#### Matriz transpuesta

In [113]:
z = np.array([y, y**2])
z

array([[ 4,  5,  6],
       [16, 25, 36]])

Las dimensiones de la matriz `z`son `(2,3)` antes de ser transpuesta:

In [114]:
z.shape

(2, 3)

Utilizando `.T` se obvitene su transposición:

In [115]:
z.T

array([[ 4, 16],
       [ 5, 25],
       [ 6, 36]])

El número de filas se ha intercambiado por el número de columnas:

In [116]:
z.T.shape

(3, 2)

#### Otras operaciones
Mediante `.dtype` se puede obtener el tipo de dato de los elementos del vector:

In [117]:
z.dtype

dtype('int32')

El método `.astype` permite convertir los elementos a un tipo determinado:

In [119]:
z = z.astype('f')
z.dtype

dtype('float32')

### Funciones matemáticas

Numpy prove varias funciones matemáticas que pueden ser ejecutadas sobre vectores:

In [125]:
a = np.array([-4, -2, 1, 3, 5])

In [121]:
a.sum()

3

In [122]:
a.max()

5

In [123]:
a.min()

-4

In [130]:
a.mean() # Promedio

0.6

In [127]:
a.std() # Desviación estándar

3.2619012860600183

Los métodos `argmax` y `argmin` devuelven el índice de los valores máximos y mínimos de un vector:

In [128]:
a.argmax()

4

In [129]:
a.argmin()

0

### Indexación / Rebanado (slicing)

In [131]:
s = np.arange(13)**2
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144],
      dtype=int32)

Mediante el uso de corchetes se obtiene el valor en un índice específico, teniendo en cuenta que los índices comienzan en cero.

In [132]:
s[0], s[4], s[-1]

(0, 16, 144)

Los dos puntos permiten indicarle un rango al vector, es decir, `array[inicio:fin]`

Si no se especifican los índices de inicio y de fin, por defecto se tomará el inicio y el fin del vector.

In [133]:
s[1:5]

array([ 1,  4,  9, 16], dtype=int32)

Con números negativos se puede contar hacia atrás:

In [134]:
s[-4:]

array([ 81, 100, 121, 144], dtype=int32)

Utilizando una segunda vez los dos puntos se indica la cantidad de índices a saltear en la secuencia, `array[inicio:fin:salto]`.

En este ejemplo comenzamos desde el quinto elemento desde el final y contando hacia atrás de dos en dos hasta llegar al comienzo del vector:

In [135]:
s[-5::-2]

array([64, 36, 16,  4,  0], dtype=int32)

#### Ejemplos con matrices

In [136]:
r = np.arange(36)
r.resize((6, 6))
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

Mediante corchetes se puede indexar por filas y columnas:

In [137]:
r[2, 2] # matriz[fila, columna]`

14

Con los dos puntos se puede elegir un rango de filas o columnas:

In [138]:
r[3, 3:6]

array([21, 22, 23])

En este caso seleccionamos todas las filas hasta la fila 2 (sin incluirla) y todas las columnas hasta la última (sin incluirla tampoco):

In [139]:
r[:2, :-1]

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10]])

Esta es una sección o rebanada de la última fila salteando de a dos números:

In [140]:
r[-1, ::2]

array([30, 32, 34])

También se puede acceder a elementos de la matriz basados en una condición. En este ejemplo seleccionamos los valores de la matriz que sean mayores a 30 (también se puede usar `np.where`):

In [141]:
r[r > 30]

array([31, 32, 33, 34, 35])

En este otro caso asignamos el número 30 a todos aquellos valores de la matriz que sean menores a 30:

In [142]:
r[r > 30] = 30
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

### Copia de datos

Es necesario ser cuidados al momento de copiar y modificar arreglos con NumPy.


En el siguiente ejemplo, `r2` es una rebanada de  `r`:

In [143]:
r2 = r[:3,:3]
r2

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

Luego establecemos el valor 0 a cada uno de los elementos de la nueva matriz:

In [144]:
r2[:] = 0
r2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

Pero en este caso la matriz `r` también ha sido modificada y los valores originales en esas posiciones se perdieron:

In [145]:
r

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

Para evitar esto se puede utilizar el método `copy` para crear una copia que no afectará a la matriz original:

In [146]:
r_copy = r.copy()
r_copy

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

Cuando modificamos ahora la matriz `r_copy`, no se aplicarán cambios sobre `r`:

In [147]:
r_copy[:] = 10
print(r_copy, '\n')
print(r)

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]] 

[[ 0  0  0  3  4  5]
 [ 0  0  0  9 10 11]
 [ 0  0  0 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 30 30 30 30 30]]


### Iteraciones sobre arreglos

En el siguiente ejemplo se crea primero un arreglo de 4 filas y 3 columnas compuesto por números aleatorios entre 0 y 9:

In [148]:
test = np.random.randint(0, 10, (4,3))
test

array([[8, 8, 7],
       [3, 2, 9],
       [1, 5, 1],
       [1, 5, 7]])

Iteración por fila:

In [149]:
for fila in test:
    print(fila)

[8 8 7]
[3 2 9]
[1 5 1]
[1 5 7]


Iteración por índice:

In [150]:
for i in range(len(test)):
    print(test[i])

[8 8 7]
[3 2 9]
[1 5 1]
[1 5 7]


Iteración por fila e índice:

In [151]:
for i, row in enumerate(test):
    print('row', i, 'is', row)

row 0 is [8 8 7]
row 1 is [3 2 9]
row 2 is [1 5 1]
row 3 is [1 5 7]


Con el método `zip` se puede iterar sobre múltiples objetos iterables:

In [152]:
test2 = test**2
test2

array([[64, 64, 49],
       [ 9,  4, 81],
       [ 1, 25,  1],
       [ 1, 25, 49]], dtype=int32)

In [154]:
for i, j in zip(test, test2):
    print(i,'+',j,'=',i+j)

[8 8 7] + [64 64 49] = [72 72 56]
[3 2 9] + [ 9  4 81] = [12  6 90]
[1 5 1] + [ 1 25  1] = [ 2 30  2]
[1 5 7] + [ 1 25 49] = [ 2 30 56]
