# 2. La biblioteca numérica de Python (NumPy)

[NumPy](http://www.numpy.org/) es un paquete muy utilizado en la comunidad de *data science* que nos permite trabajar eficientemente con vectores y matrices en Python.

In [1]:
import numpy as np

## 2.1. Creación de arreglos
Para crear un arreglo se puede simplemente crear primero una lista y convertirla a un arreglo:

In [2]:
lista = [1, 2, 3]
x = np.array(lista)
x

array([1, 2, 3])

También se puede pasar la lista por parámetro directamente:

In [3]:
y = np.array([4, 5, 6])
y

array([4, 5, 6])

Si por parámetro se pasa una lista de lista se pueden crear arreglos multidimensionales:

In [4]:
m = np.array([[7, 8, 9], [10, 11, 12]])
m

array([[ 7,  8,  9],
       [10, 11, 12]])

Se puede acceder al atributo `shape` para averiguar las dimensiones del arreglo (filas, columnas): 

In [5]:
m.shape

(2, 3)

El método `arange` devuelve un arreglo con valores separados uniformemente dentro de un intervalo dado:

In [6]:
n = np.arange(0, 30, 2) # comienza en 0 hasta 30 yendo de 2 en 2
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

El método `reshape` devuelve un arreglo con los mismos valores pero con otra forma:

In [7]:
n = n.reshape(3, 5) # convierte a 3x5
n

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

El método `linspace` es muy similar a `arange` excepto que le decimos cuántos números deseamos que devuelva y se encargará de dividirlos uniformemente dentro del rango solicitado:

In [8]:
o = np.linspace(0, 4, 9) # devuelve 9 números separados uniformemente entre 0 y 4
o

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

El método `resize` cambia las dimensiones de un mismo arreglo:

In [9]:
o.resize(3, 3)
o

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])

NumPy también tiene varias otras funciones y atajos rápidos para crear arreglos específicos.

El método `ones` devuelve un nuevo arreglo lleno de unos con las dimensiones especificadas:

In [10]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

Análogamente, el método `zeros` devuelve un arreglo lleno de ceros con las dimensiones especificadas:

In [11]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

El método `eye` devuelve un arreglo bidimensional con unos en la diagonal principal y ceros en las demás posiciones:

In [12]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

El método `diag` crea una matriz diagonal:

In [13]:
np.diag(y)

array([[4, 0, 0],
       [0, 5, 0],
       [0, 0, 6]])

Para crear una matriz con valores repetidos se pueden pasar listas repetidas o el método `repeat` de NumPy:

In [14]:
np.array([1, 2, 3] * 3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [15]:
np.repeat([1, 2, 3], 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

## 2.2. Combinación de arreglos

In [16]:
p = np.ones([2, 3], int)
p

array([[1, 1, 1],
       [1, 1, 1]])

El método `vstack` permite apilar arreglos verticalmente:

In [17]:
np.vstack([p, 2*p])

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2]])

Análogamente, el método `hstack` permite apilar arreglos en secuencia horizontal:

In [18]:
np.hstack([p, 2*p])

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

## 2.3. Operaciones
Los operadores `+`, `-`, `*`, `/` y `**` permiten realizar adiciones, substracciones, multiplicaciones, divisiones y potenciaciones sobre cada elemento de un arreglo:

In [19]:
print(x + y) #  [1 2 3] + [4 5 6] = [5  7  9]
print(x - y) #  [1 2 3] - [4 5 6] = [-3 -3 -3]

[5 7 9]
[-3 -3 -3]


In [20]:
print(x * y) #  [1 2 3] * [4 5 6] = [4  10  18]
print(x / y) #  [1 2 3] / [4 5 6] = [0.25  0.4  0.5]

[ 4 10 18]
[0.25 0.4  0.5 ]


In [21]:
print(x**2) #  [1 2 3] ^2 =  [1 4 9]

[1 4 9]


### 2.3.1. Producto escalar

$ \begin{bmatrix}x_1 \ x_2 \ x_3\end{bmatrix}
\cdot
\begin{bmatrix}y_1 \\ y_2 \\ y_3\end{bmatrix}
= x_1 y_1 + x_2 y_2 + x_3 y_3$

In [22]:
x.dot(y) # producto escalar  1*4 + 2*5 + 3*6

32

In [23]:
z = np.array([y, y**2])
print(len(z)) # número de filas en la matriz

2


### 2.3.2. Matriz transpuesta

In [24]:
z = np.array([y, y**2])
z

array([[ 4,  5,  6],
       [16, 25, 36]])

Las dimensiones de la matriz `z` son `(2,3)` antes de ser transpuesta:

In [25]:
z.shape

(2, 3)

Utilizando `.T` se obvitene su transposición:

In [26]:
z.T

array([[ 4, 16],
       [ 5, 25],
       [ 6, 36]])

El número de filas se ha intercambiado por el número de columnas:

In [27]:
z.T.shape

(3, 2)

### 2.3.4. Otras operaciones
Mediante `.dtype` se puede obtener el tipo de dato de los elementos del arreglo:

In [28]:
z.dtype

dtype('int32')

El método `.astype` permite convertir los elementos a un tipo determinado:

In [29]:
z = z.astype('f')
z.dtype

dtype('float32')

## 2.4 Funciones matemáticas

Numpy prove varias funciones matemáticas que pueden ser ejecutadas sobre arreglos:

In [30]:
a = np.array([-4, -2, 1, 3, 5])

In [31]:
a.sum()

3

In [32]:
a.max()

5

In [33]:
a.min()

-4

In [34]:
a.mean() # Promedio

0.6

In [35]:
a.std() # Desviación estándar

3.2619012860600183

Los métodos `argmax` y `argmin` devuelven el índice de los valores máximos y mínimos de un arreglo:

In [36]:
a.argmax()

4

In [37]:
a.argmin()

0

## 2.5. Indexación / Rebanado (slicing)

In [38]:
s = np.arange(13)**2
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144],
      dtype=int32)

Mediante el uso de corchetes se obtiene el valor en un índice específico, teniendo en cuenta que los índices comienzan en cero.

In [39]:
s[0], s[4], s[-1]

(0, 16, 144)

Los dos puntos permiten indicarle un rango al arreglo, es decir, `array[inicio:fin]`

Si no se especifican los índices de inicio y de fin, por defecto se tomará el inicio y el fin del arreglo.

In [40]:
s[1:5]

array([ 1,  4,  9, 16], dtype=int32)

Con números negativos se puede contar hacia atrás:

In [41]:
s[-4:]

array([ 81, 100, 121, 144], dtype=int32)

Utilizando una segunda vez los dos puntos se indica la cantidad de índices a saltear en la secuencia, `array[inicio:fin:salto]`.

En este ejemplo comenzamos desde el quinto elemento desde el final y contando hacia atrás de dos en dos hasta llegar al comienzo del arreglo:

In [42]:
s[-5::-2]

array([64, 36, 16,  4,  0], dtype=int32)

### 2.5.1. Ejemplos con matrices

In [43]:
r = np.arange(36)
r.resize((6, 6))
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

Mediante corchetes se puede indexar por filas y columnas:

In [44]:
r[2, 2] # matriz[fila, columna]`

14

Con los dos puntos se puede elegir un rango de filas o columnas:

In [45]:
r[3, 3:6]

array([21, 22, 23])

En este caso seleccionamos todas las filas hasta la fila 2 (sin incluirla) y todas las columnas hasta la última (sin incluirla tampoco):

In [46]:
r[:2, :-1]

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10]])

Esta es una sección o rebanada de la última fila salteando de a dos números:

In [47]:
r[-1, ::2]

array([30, 32, 34])

También se puede acceder a elementos de la matriz basados en una condición. En este ejemplo seleccionamos los valores de la matriz que sean mayores a 30 (también se puede usar `np.where`):

In [48]:
r[r > 30]

array([31, 32, 33, 34, 35])

En este otro caso asignamos el número 30 a todos aquellos valores de la matriz que sean menores a 30:

In [49]:
r[r > 30] = 30
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

## 2.6. Copia de datos

Es necesario ser cuidados al momento de copiar y modificar arreglos con NumPy.


En el siguiente ejemplo, `r2` es una rebanada de  `r`:

In [50]:
r2 = r[:3,:3]
r2

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

Luego establecemos el valor 0 a cada uno de los elementos de la nueva matriz:

In [51]:
r2[:] = 0
r2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

Pero en este caso la matriz `r` también ha sido modificada y los valores originales en esas posiciones se perdieron:

In [52]:
r

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

Para evitar esto se puede utilizar el método `copy` para crear una copia que no afectará a la matriz original:

In [53]:
r_copy = r.copy()
r_copy

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

Cuando modificamos ahora la matriz `r_copy`, no se aplicarán cambios sobre `r`:

In [54]:
r_copy[:] = 10
print(r_copy, '\n')
print(r)

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]] 

[[ 0  0  0  3  4  5]
 [ 0  0  0  9 10 11]
 [ 0  0  0 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 30 30 30 30 30]]


## 2.7. Iteraciones sobre arreglos

En el siguiente ejemplo se crea primero un arreglo de 4 filas y 3 columnas compuesto por números aleatorios entre 0 y 9:

In [55]:
test = np.random.randint(0, 10, (4,3))
test

array([[5, 8, 7],
       [9, 9, 0],
       [9, 0, 7],
       [2, 4, 7]])

Iteración por fila:

In [56]:
for fila in test:
    print(fila)

[5 8 7]
[9 9 0]
[9 0 7]
[2 4 7]


Iteración por índice:

In [57]:
for i in range(len(test)):
    print(test[i])

[5 8 7]
[9 9 0]
[9 0 7]
[2 4 7]


Iteración por fila e índice:

In [58]:
for i, row in enumerate(test):
    print('row', i, 'is', row)

row 0 is [5 8 7]
row 1 is [9 9 0]
row 2 is [9 0 7]
row 3 is [2 4 7]


Con el método `zip` se puede iterar sobre múltiples objetos iterables:

In [59]:
test2 = test**2
test2

array([[25, 64, 49],
       [81, 81,  0],
       [81,  0, 49],
       [ 4, 16, 49]], dtype=int32)

In [60]:
for i, j in zip(test, test2):
    print(i,'+',j,'=',i+j)

[5 8 7] + [25 64 49] = [30 72 56]
[9 9 0] + [81 81  0] = [90 90  0]
[9 0 7] + [81  0 49] = [90  0 56]
[2 4 7] + [ 4 16 49] = [ 6 20 56]
